Repository UKPythonAssociation/ukpa-internaldocs, pull requests merged in 2019-12, with the labels that each got.

#8 Add a proposal selection policy document.
  source/policies/index.rst
  source/policies/programme-selection-policy.rst
Labels: Trustee Meeting Decision

#7 Add financial assistance policy.
  source/policies/financial-assistance-for-pyconuk.rst
  source/policies/index.rst
Labels: Trustee Meeting Decision

#6 Write expenses policy.
  source/policies/expenses-policy.rst
  source/policies/index.rst
Labels: Trustee Meeting Decision

#15 Add general meeting minutes
  source/index.rst
  source/meetings/general-meeting-30-nov-2019.rst
  source/meetings/index.rst
Labels: Trustee Meeting Decision

#13 Add the membership policy
  source/policies/index.rst
  source/policies/membership.rst
Labels: Trustee Meeting Decision

#18 Add PyLondinium decision
  source/decisions/index.rst
  source/decisions/pylondinium.rst
  source/index.rst
Labels: Trustee Meeting Decision

#19 Add 2019 AGM minutes
  source/meetings/general-meeting-14-sep-2019.rst
  source/meetings/index.rst
Labels: Minutes

#14 Add changelog.md
  CHANGELOG.md
Labels: Admin

#24 Add 2018 AGM minutes
  source/meetings/general-meeting-15-sep-2018.rst
  source/meetings/index.rst
Labels: Minutes

#23 Add resolution to sign UKPATL deeds
  source/decisions/index.rst
  source/decisions/ukpatl-deeds.rst
Labels: Resolution Decision
